### ISSUE TITLE
Uncaught RuntimeException: DB_NAME, DB_USER, DB_PASSWORD

### ISSUE THREAD

**Issue by ccambournac** [wecodemore/wpstarter#63] opened 2017-04-25 08:11 UTC
Hi, it appears that the starter breaks if database is accessed without password, which is quite often for local development.

**Comment by gmazzap** [comment] 2017-04-25 09:47
Hi @ccambournac this is an issue we had that is caused by Windows where environment variables might "survive" the request, depending on the version of PHP that is used. 

This issue was tracked here #49 but it should be fixed from version 2.4+. Are you experiencing this with latest version of WP Starter (2.4.1)?

**Comment by ccambournac** [comment] 2017-04-25 10:44
Hi @gmazzap yes indeed, with the latest version. Cloned today :)
And working with PHP 7 on Windows 7.

**Comment by ccambournac** [comment] 2017-04-25 12:12
I saw the tracked issue you mention @gmazzap but as far as I can see, the `settings` method of the `Helpers` class does not accept variables with empty values. Thought it was only that.

**Comment by christophrumpel** [comment] 2018-04-20 15:11
any news here? Facing the same problem with local empty DB password.

**Comment by christophrumpel** [comment] 2018-04-20 16:18
just removed it from the require-array in `Helpers.php` to make it work for now. Is there a reason why it should be required?

**Comment by gmazzap** [comment] 2018-05-07 21:33
Yep, I will remove it.

**Comment by gmazzap** [comment] 2018-05-07 21:54
Thanks @ccambournac and @christophrumpel fixed with [2.4.3](https://github.com/wecodemore/wpstarter/releases/tag/2.4.3)

**Closed by gmazzap** 2018-05-07 21:54 UTC
Labels: ->Assigned, ~Code
